### ISSUE TITLE
Document how to use Pathfinder to initialize PPLs 

### ISSUE THREAD

**Issue by sethaxen** [sethaxen/Pathfinder.jl#13]
_Originally posted by @joshualeond in https://github.com/sethaxen/Pathfinder.jl/issues/10#issuecomment-955859874_:

> Exciting to see this work being done in Julia! Do you think it would make sense to include an example of how you could use the results of this package to initialize MCMC in Turing/Soss/Stan/etc?

**Comment by sethaxen** [comment]
This is a great idea! We can at least initialize from the random points Pathfinder returns. It's even more useful if we can initialize the metric.

Ideally we would also refine the metric using the adaptation scheme explained in https://arxiv.org/abs/1905.11916, but that will come with AdvancedHMC integration either here or in AdvancedHMC. See https://github.com/TuringLang/AdvancedHMC.jl/issues/282

**Comment by joshualeond** [comment]
Thanks! I hadn't heard of the _metric_ used in Stan's HMC before. I don't see the Euclidean metric referenced in the Pathfinder paper though. Is it mentioned under a different name or is this something that hasn't been done before in Stan?

**Comment by sethaxen** [comment]
The metric is sometimes called the mass matrix, and its use in Stan is explained at https://mc-stan.org/docs/2_28/reference-manual/hmc-algorithm-parameters.html#euclidean-metric . Typically the inverse of the metric is adapted by setting it to the sample covariance or a diagonal estimate of it, so sometimes people just talk about estimating the sample covariance. This is what they're talking about in the discussion of the Pathfinder paper:

![Screenshot from 2021-11-02 09-09-11](https://user-images.githubusercontent.com/8673634/139809306-6ec7fa92-3210-46b5-afb6-8a320fc7be6f.png)

The Bales et al paper is the one I linked to above. So you can see how Pathfinder gives a different approach for setting the covariance instead of estimating it from samples, which one could then use to initialize the metric adaptation.
