### ISSUE TITLE
multipathfinder - no method matching iterate

### ISSUE THREAD

**Issue by paschermayr** [sethaxen/Pathfinder.jl#72]
Dear Seth, 

Cool package! I have some troubles running the multi-pathfinder with the most recent release. The actual computation works fine, but it seems like an iterator is not working when collecting the draws (line 196 in multipath.jl). MWE: 

```julia
using Distributions #Distributions v0.25.59
using Pathfinder #Pathfinder v0.4.5
using ForwardDiff


function targetclosure(data)
    function target(θ)
        μ = sum(θ)
        return sum( logpdf.(Normal(μ, 1.0), data) )
    end
end

target = targetclosure(randn(1000))
θ = randn(2)
∇logp(θ) = ForwardDiff.gradient(target, θ)

#using Pathfinder works -> posterior mean of θ == 0
result = pathfinder(target, ∇logp; init = θ)

#using multipathfinder
Nruns = 10
θ_initial = [zeros(2) for _ in Base.OneTo(Nruns)]
for iter in eachindex(θ_initial)
    θ_initial[iter] = randn(2)
end

q, ϕ, component_ids = multipathfinder(
    target,
    ∇logp,
    Nruns;
    init = θ_initial
) #MethodError: no method matching iterate(::MultiPathfinderResult{Tuple{var"#target#8"{Vector{Float64}}, typeof(∇logp)}

```

Best regards, 
Patrick

**Comment by sethaxen** [comment]
Similar to `pathfinder`, which returns a `PathfinderResult`, the return value of `multipathfinder` is a `MultiPathfinderResult`, which does not have an implemented `iterate` method. This works:

```julia
julia> result_multi = multipathfinder(
           target,
           ∇logp,
           Nruns;
           init = θ_initial
       )
Multi-path Pathfinder result
  runs: 10
  draws: 10
  Pareto shape diagnostic: 0.69 (ok)
```

Previously, `multipathfinder` did indeed return a tuple of objects. Is there a place in the documentation that you based your code on that needs to be updated?

**Comment by paschermayr** [comment]
Thank you! I must have gotten the function call from the docs of an old version. Can be closed.

**Comment by paschermayr** [comment]
@sethaxen : Sorry to bump an old thread, but it seems like its not possible to use this example with the current Pathfinder.gl version anymore. I get the same error as the CI tests in Pathfinder.jl.

MWE from a newly created environment:
```
#=
[31c24e10] Distributions v0.25.65
[f6369f11] ForwardDiff v0.10.30
[b1d3bc72] Pathfinder v0.4.6
=#
using Distributions
using Pathfinder
using ForwardDiff


function targetclosure(data)
    function target(θ)
        μ = sum(θ)
        return sum( logpdf.(Normal(μ, 1.0), data) )
    end
end

target = targetclosure(randn(1000))
θ = randn(2)
∇logp(θ) = ForwardDiff.gradient(target, θ)

#using Pathfinder works -> posterior mean of θ == 0
result = pathfinder(target, ∇logp; init = θ) #MethodError: no method matching size(::Pathfinder.WoodburyPDMat{Float64, LinearAlgebra.Diagonal{Float64, Vector{Float64}}, Matrix{Float64}, Matrix{Float64}, LinearAlgebra.Diagonal{Float64, Vector{Float64}}, LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}}, LinearAlgebra.UpperTriangular{Float64, Matrix{Float64}}})

```

**Comment by sethaxen** [comment]
@paschermayr thanks for the heads up! I had not noticed the CI failing.

It seems this is due to a recent change in https://github.com/JuliaStats/PDMats.jl/pull/170, which deleted their `size(::AbstractPDMat)` method.

**Comment by sethaxen** [comment]
#80 fixes this issue

**Comment by paschermayr** [comment]
Thank you for your work!
