### ISSUE TITLE
WoodburyPDMat and unwhitening and square norms

### ISSUE THREAD

**Issue by mschauer** [sethaxen/Pathfinder.jl#77]
For 
```
L = cholesky(Symmetric(inv(Matrix(pf_result.fit_distribution.Σ)))).L
```
I want to compute ` norm(L\x)^2`  and `F.L'\randn(d)`. Can I express this with the `WoodburyPDMat` interface?

**Comment by sethaxen** [comment]
Correct me if I'm wrong, but `norm(L\x)^2` is just `dot(inv(L) * x, inv(L) * x) == dot(x, inv(L L'), x)`, which is the same as `dot(x, Σ, x)`. This is computable as `PDMats.quad(Σ, x)`.

If you _really_ want the Cholesky decomposition, then no, there's no way to use the WoodburyPDMat interface to compute `F.L'\randn(d)`. But if `y = F.L' \ z`, for std normal `z`, then `y` is mv-normally distributed with covariance of `Σ`, and you can draw these samples a different way with `PDMats.unwhiten(Σ, randn(d))`.

**Comment by mschauer** [comment]
You answer the questions I should have asked, thank you!
